// This file is auto-generated by @hey-api/openapi-ts

export const GameTurnRequestSchema = {
    type: 'object',
    properties: {
        turnNumber: {
            type: 'number'
        },
        userSelection: {
            type: 'string',
            enum: ['Rock', 'Paper', 'Scissors']
        }
    },
    required: ['turnNumber', 'userSelection']
} as const;

export const GameTurnResponseSchema = {
    type: 'object',
    properties: {
        turnNumber: {
            type: 'number'
        },
        gameResult: {
            type: 'string',
            enum: ['Winner', 'Loser', 'Tie']
        },
        serverSelection: {
            type: 'string'
        }
    },
    required: ['gameResult', 'serverSelection', 'turnNumber']
} as const;

export const GameConfigSchema = {
    type: 'object',
    properties: {
        numberOfGames: {
            type: 'number'
        },
        gameChoices: {
            type: 'array',
            items: {
                type: 'string',
                enum: ['Rock', 'Paper', 'Scissors']
            }
        }
    },
    required: ['gameChoices', 'numberOfGames']
} as const;